server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    hbm2ddl.auto: update
    show_sql: false